---

version: 0.2
phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - docker pull $CONTAINER_REPOSITORY_URL:$REF_NAME || true
  build:
    commands:
      - docker build --cache-from $CONTAINER_REPOSITORY_URL:$REF_NAME --tag $CONTAINER_REPOSITORY_URL:$REF_NAME --tag $CONTAINER_REPOSITORY_URL:v$CODEBUILD_BUILD_ID services/app
      - docker network create shared
      - docker push $CONTAINER_REPOSITORY_URL:$REF_NAME
      - docker run --network shared --name db -d postgres
      - docker run --network shared $CONTAINER_REPOSITORY_URL mix test
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:v$CODEBUILD_BUILD_ID
