---

version: 0.2
phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - docker pull $CONTAINER_REPOSITORY_URL:$REF_NAME || true
  build:
    commands:
      - docker build --cache-from $CONTAINER_REPOSITORY_URL:$REF_NAME --tag $CONTAINER_REPOSITORY_URL:$REF_NAME --tag $CONTAINER_REPOSITORY_URL:v$CODEBUILD_RESOLVED_SOURCE_VERSION services/app
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:$REF_NAME
      - docker run -d postgres
      - docker run $CONTAINER_REPOSITORY_URL mix test
      - docker push $CONTAINER_REPOSITORY_URL:v$CODEBUILD_RESOLVED_SOURCE_VERSION
