---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-proxy-deployment
  labels:
    app: sql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-proxy
  template:
    metadata:
      labels:
        app: sql-proxy
    spec:
      containers:
        - name: sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
            - "/cloud_sql_proxy"
            - "--dir=/cloudsql"
            - "-instances=hexlet-basics:europe-west3:master=tcp:0.0.0.0:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
