apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@hexlet.io
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: kirill.m@hexlet.io
            apiKeySecretRef:
              name: cloudflare-credentials
              key: CF_API_KEY
