# ---

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: users-code
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
