provider: cloudflare

rbac:
  create: true

resources:
  requests:
    cpu: 10m

extraEnv:
  # - envFrom:
  #     - secretRef:
  #         name: cloudflare-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: CF_API_KEY
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: CF_API_EMAIL
