provider: cloudflare

rbac:
  create: true

resources:
  requests:
    cpu: 10m

extraEnv:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: api_key
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: email
