ansible_python_interpreter: /usr/local/bin/python3

hexlet_basics_repository: "git@github.com:hexlet-basics/hexlet_basics.git"
hexlet_basics_directory_to_clone: /var/tmp/hexlet_basics
hexlet_basics_image_name: "hexlet/hexlet-basics"
