ansible_python_interpreter: "/usr/bin/env python3"

hexlet_basics_repository: "git@github.com:hexlet-basics/hexlet_basics.git"
hexlet_basics_directory_to_clone: /var/tmp/hexlet_basics
hexlet_basics_image_name: "hexlet/hexlet-basics"
hexlet_basics_run_user: ubuntu
hexlet_basics_run_user_home: /home/ubuntu
hexlet_basics_port: 3000

docker_install_compose: no
