---

substitutions:
  _SLACK_WEBHOOK_: null

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/app:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/app:latest',
      # '--file', 'services/app/Dockerfile',
      'services/app'
    ]
  - name: 'docker/compose:1.15.0'
    args: [
      '--project-directory', 'services/app',
      '-f', 'services/app/docker-compose.yml',
      'run',
      'sut'
    ]
  - name: 'technosophos/slack-notify'
    args: [
      '-e', 'SLACK_WEBHOOK=${_SLACK_WEBHOOK}',
      '-e', 'SLACK_MESSAGE=hello',
      '-e', 'SLACK_TITLE="title"',
      '-e', 'SLACK_USERNAME=cloudbuild'
    ]
    env:

timeout: "1200s"
images: ['gcr.io/$PROJECT_ID/app:latest']
