---

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/app:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/app:latest',
      # '--file', 'services/app/Dockerfile',
      'services/app'
    ]
  - name: 'docker/compose:1.15.0'
    args: [
      '--project-directory', 'services/app',
      '-f', 'services/app/docker-compose.yml',
      'run',
      'sut'
    ]
  - name: 'technosophos/slack-notify'
    args: [
    ]
    env:
      - 'SLACK_WEBHOOK=${_SLACK_WEBHOOK}'
      - 'SLACK_MESSAGE=App was built (${SHORT_SHA})'
      - 'SLACK_TITLE="${PROJECT_ID}:${TAG_NAME}${BRANCH_NAME}"'
      - 'SLACK_USERNAME=cloudbuild'

timeout: "1200s"
images: ['gcr.io/$PROJECT_ID/app:$TAG_NAME']
