---

substitutions:
  _SLACK_WEBHOOK: 'key'
  _MASTER_IMAGE: 'gcr.io/hexlet-basics/app:master'

steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'pull',
      '${_MASTER_IMAGE}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', '${_MASTER_IMAGE}',
      '--tag', 'app',
      'services/app'
    ]

  - name: 'docker/compose:1.19.0'
    args: [
      '-f', 'services/app/docker-compose.test.yml',
      'run',
      'test'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'app',
      'gcr.io/hexlet-basics/app:${TAG_NAME}${BRANCH_NAME}'
    ]

  - name: 'technosophos/slack-notify'
    args: [
    ]
    env:
      - 'SLACK_WEBHOOK=${_SLACK_WEBHOOK}'
      - 'SLACK_MESSAGE=App was built (${SHORT_SHA})'
      - 'SLACK_TITLE="hexlet-basics:${TAG_NAME}${BRANCH_NAME}"'
      - 'SLACK_USERNAME=cloudbuild'

timeout: "1200s"
images: ['gcr.io/hexlet-basics/app:${TAG_NAME}${BRANCH_NAME}']
