---

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/app:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/app:latest',
      # '--file', 'services/app/Dockerfile',
      'services/app'
    ]
  - name: 'docker/compose:1.15.0'
    args: [
      '--project-directory', 'services/app',
      '-f', 'services/app/docker-compose.yml',
      'run',
      'sut'
    ]

images: ['gcr.io/$PROJECT_ID/app:latest']
