---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      automountServiceAccountToken: true
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.5.5
          args:
            - --source=service
            - --source=ingress
            - --provider=cloudflare
            # - --log-level=debug
            - --cloudflare-proxied
            - --policy=upsert-only
            - --registry=txt
          resources:
            requests:
              cpu: 10m
          env:
            - name: FOO
              value: "3"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: api_key
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: email
