---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:

  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web

    spec:

      containers:

        - name: nginx
          imagePullPolicy: Always
          image: gcr.io/hexlet-basics/nginx
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m

        - name: phoenix
          imagePullPolicy: Always
          image: gcr.io/hexlet-basics/app
          resources:
            requests:
              cpu: 10m
          command:
            - make
            - start
          ports:
            - containerPort: 4000
          env:
            - name: MIX_ENV
              value: prod
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: production
            - name: DB_HOSTNAME
              value: sql-proxy-service
            - name: DB_POOL_SIZE
              value: 10
            - name: DB_NAME
              value: hexlet_basics_prod
            - name: FORCE
              value: '4'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
