---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:

  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    # type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web

    spec:

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock

      containers:

        - name: nginx
          imagePullPolicy: Always
          image: gcr.io/hexlet-basics/nginx:v89
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
          env:
            - name: NGINX_SERVER_ADDRESS
              value: localhost

        - name: phoenix
          securityContext:
            privileged: true
          imagePullPolicy: Always
          image: gcr.io/hexlet-basics/app:v89
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          resources:
            requests:
              cpu: 10m
          command:
            - make
            - start
          ports:
            - containerPort: 4000
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path
            - mountPath: /var/run/docker.sock
              name: docker-sock
            # - mountPath: /opt
            #   name: users-code
          env:
            - name: MIX_ENV
              value: prod
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: production
            - name: DB_HOSTNAME
              value: sql-proxy-service
            - name: DB_POOL_SIZE
              value: "10"
            - name: DB_NAME
              value: hexlet_basics_prod
            - name: FORCE
              value: '10'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: GITHUB_CLIENT_ID_RU
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: client_id
            - name: GITHUB_CLIENT_SECRET_RU
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: client_secret
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: hexlet-basics-secrets
                  key: secret_key_base
