piVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: certificate
  commonName: '*.hexlet.io'
  dnsNames:
  - hexlet.io
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - '*.hexlet.io'
      - hexlet.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
