---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: "hexlet_basics_image_tag"
      prompt: "Hexlet Basics image tag"
      private: no

  tasks:
    - set_fact: hexlet_basics_image_tag={{ hexlet_basics_image_tag }}
      tags: always

    - name: notify slack
      local_action:
        module: slack
        domain: hexlet.slack.com
        token: "{{ hexlet_basics_vault_slack_token }}"
        msg: "Hexlet Basics deploy started: {{ hexlet_basics_mix_env }}:{{ hexlet_basics_image_tag }}"
        channel: "#operation"
        username: "{{ ansible_ssh_user }}"
      run_once: yes

- hosts: webservers
  gather_facts: no
  # become: yes
  # become_user: "{{ hexlet_basics_run_user }}"

  tasks:

    # - docker_container:
    #     recreate: yes
    #     name: hexlet-web-nginx
    #     image: hexlet/hexlet-web-nginx
    #     state: started
    #     restart_policy: always
    #     ports:
    #       - "80:80"
    #       - "443:443"
    #     networks:
    #       - name: "{{hexlet_web_network}}"
    #   tags: [webserver]

    - name: download image
      docker_image:
        name: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        force: yes

    - name: run migrations
      docker_container:
        recreate: yes
        name: hexlet-basics-migrations
        command: "mix ecto.migrate"
        image: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        state: started
        # log_driver: awslogs
        # log_options:
        #   awslogs-group: hexlet-production
        #   awslogs-stream: hexlet-web
        #   awslogs-region: '{{ aws_region }}'
        env_file: "{{ hexlet_basics_env_file }}"
        env:
          MIX_ENV: production
          NODE_ENV: production
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      run_once: yes
      tags: [webserver]

    - name: start application
      docker_container:
        recreate: yes
        name: hexlet-basics-web
        image: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        state: started
        # log_driver: awslogs
        # log_options:
        #   awslogs-group: hexlet-production
        #   awslogs-stream: hexlet-web
        #   awslogs-region: '{{ aws_region }}'
        restart_policy: always
        env_file: "{{ hexlet_basics_env_file }}"
        ports:
          - "80:3000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp:/tmp"
          - "/opt:/opt"
          - "/var/tmp:/var/tmp"
      tags: [webserver]

- hosts: all
  gather_facts: no
  tasks:

    # - name: "Send deploy hook to Rollbar"
    #   local_action: shell curl https://api.rollbar.com/api/1/deploy/ \
    #       -F access_token="{{ hexlet_basics_vault_rollbar_backend_token }}" \
    #       -F environment="{{ hexlet_basics_mix_env }}" \
    #       -F revision="{{ hexlet_basics_image_tag }}" \
    #       -F local_username="{{ ansible_ssh_user }}"
    #   run_once: yes

    - name: notify slack
      local_action:
        module: slack
        domain: hexlet.slack.com
        token: "{{ hexlet_basics_vault_slack_token }}"
        msg: "Hexlet Basics deploy completed ({{ hexlet_basics_mix_env }})"
        channel: "#operation"
        username: "{{ ansible_ssh_user }}"
      run_once: yes
