---
- hosts: all
  gather_facts: false
  vars_prompt:
    - name: "hexlet_basics_image_tag"
      prompt: "Hexlet Basics image tag"
      private: false

  tasks:
    - set_fact: hexlet_basics_image_tag={{ hexlet_basics_image_tag }}
      tags: always

    - name: notify slack
      local_action:
        module: slack
        domain: hexlet.slack.com
        token: "{{ hexlet_basics_vault_slack_token }}"
        msg: "Hexlet Basics deploy started: {{ hexlet_basics_mix_env }}:{{ hexlet_basics_image_tag }}"
        channel: "#operation"
        username: "{{ ansible_ssh_user }}"
      run_once: true

- hosts: webservers
  gather_facts: false
  # become: true
  # become_user: "{{ hexlet_basics_run_user }}"

  tasks:

    - template:
        src: environment.j2
        dest: "{{ hexlet_basics_env_file }}"
      tags: env

    - name: download image
      docker_image:
        name: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        force: true

    - name: run migrations
      docker_container:
        recreate: true
        detach: false
        name: hexlet-basics-migrations
        command: "mix ecto.migrate"
        image: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        state: started
        env_file: "{{ hexlet_basics_env_file }}"
        env:
          MIX_ENV: prod
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      run_once: true
      tags: [webserver]

    - name: start application
      docker_container:
        recreate: true
        name: hexlet-basics-web
        image: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        state: started
        log_driver: awslogs
        log_options:
          awslogs-group: "{{ hexlet_basics_aws_logs_group }}"
          awslogs-stream: "{{ hexlet_basics_aws_logs_stream_web }}"
          awslogs-region: '{{ hexlet_basics_aws_region }}'
        restart_policy: always
        env_file: "{{ hexlet_basics_env_file }}"
        env:
          MIX_ENV: prod
          NODE_ENV: production
        ports:
          - "80:{{ hexlet_basics_port }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp:/tmp"
          - "/opt:/opt"
          - "/var/tmp:/var/tmp"
      tags: [webserver]

    - lineinfile:
        regexp: "HEXLET_BASICS_VERSION"
        line: "HEXLET_BASICS_VERSION={{ hexlet_basics_image_tag }}"
        dest: /etc/environment
        backup: true
        state: present
      become: true

- hosts: all
  gather_facts: false
  tasks:

    - name: "Send deploy hook to Rollbar"
      local_action: shell curl https://api.rollbar.com/api/1/deploy/ \
          -F access_token="{{ hexlet_basics_vault_rollbar_access_token }}" \
          -F environment="{{ hexlet_basics_mix_env }}" \
          -F revision="{{ hexlet_basics_image_tag }}" \
          -F local_username="{{ ansible_ssh_user }}"
      run_once: true

    - name: notify slack
      local_action:
        module: slack
        domain: hexlet.slack.com
        token: "{{ hexlet_basics_vault_slack_token }}"
        msg: "Hexlet Basics deploy completed ({{ hexlet_basics_mix_env }})"
        channel: "#operation"
        username: "{{ ansible_ssh_user }}"
      run_once: true
