- hosts: all
  gather_facts: no
  tasks:
    - pip:
        name: "{{ item }}"
      with_items:
        - docker
        - docker-py

    - template:
        src: environment.j2
        dest: '../.env.development'
      tags: env

    - lineinfile:
        path: /etc/hosts
        regexp: 'hexlet-basics'
        line: '127.0.0.1 ru.hexlet-basics.test en.hexlet-basics.test # hexlet-basics'
      become: yes

