---

- hosts: all
  vars:
    langs:
      - php
      - javascript
  # gather_facts: no
  # become: yes
  # become_user: "{{ hexlet_basics_run_user }}"

  tasks:
    - name: download image
      docker_image:
        name: "hexlet/hexlet-basics-exercises-{{ item }}"
        force: yes
      with_items: "{{ langs }}"

    - name: exercises-php data container
      docker_container:
        detach: no
        recreate: yes
        name: "hexlet-basics-exercises-{{ item }}-data"
        image: "hexlet/hexlet-basics-exercises-{{ item }}"
        state: present
        volumes:
          - "/exercises-{{ item }}"
      with_items: "{{ langs }}"

    - docker_container:
        recreate: yes
        detach: no
        name: "hexlet-basics-exercises-{{ item }}"
        command: "mix x.exercises.load {{ item }}"
        image: "{{ hexlet_basics_image_name }}:{{ ansible_env.HEXLET_BASICS_VERSION }}"
        state: started
        env_file: "{{ hexlet_basics_env_file }}"
        volumes_from:
          - "hexlet-basics-exercises-{{ item }}-data"
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      with_items: "{{ langs }}"
      run_once: yes
