---

- hosts: all
  gather_facts: no
  # become: yes
  # become_user: "{{ hexlet_basics_run_user }}"

  vars:
    hexlet_basics_image_tag: latest
  tasks:

    - docker_container:
        recreate: yes
        name: hexlet-basics-exercises
        command: "mix x.exercises.load {{ hexlet_basics_language_for_loading }}"
        image: "{{ hexlet_basics_image_name }}:{{ hexlet_basics_image_tag }}"
        state: started
        # log_driver: awslogs
        # log_options:
        #   awslogs-group: hexlet-production
        #   awslogs-stream: hexlet-web
        #   awslogs-region: '{{ aws_region }}'
        env_file: "{{ hexlet_basics_env_file }}"
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      run_once: yes
