---

- hosts: all
  gather_facts: no
  # become: yes
  # become_user: "{{ hexlet_basics_run_user }}"

  tasks:
    - name: download image
      docker_image:
        name: hexlet/hexlet-basics-exercises-php
        force: yes

    - name: exercises-php data container
      docker_container:
        detach: no
        recreate: yes
        name: hexlet-basics-exercises-php-data
        image: hexlet/hexlet-basics-exercises-php
        state: present
        volumes:
        - /exercises-php

    - docker_container:
        recreate: yes
        detach: no
        name: hexlet-basics-exercises-php
        command: "mix x.exercises.load php"
        image: "{{ hexlet_basics_image_name }}:{{ lookup('env','HEXLET_BASICS_VERSION') }}"
        state: started
        env_file: "{{ hexlet_basics_env_file }}"
        volumes_from:
          - hexlet-basics-exercises-php-data
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      run_once: yes
